<?php

namespace AppBundle\Repository;

/**
 * EcoDopplerColorVenosoMiembrosInferioresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcoDopplerColorVenosoMiembrosInferioresRepository extends \Doctrine\ORM\EntityRepository
{
}
