<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EspecialidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecialidadRepository extends EntityRepository
{
		public function findForPaginator(){
		$em = $this->getEntityManager();
		$dql = "SELECT u FROM AppBundle:Especialidad u";
        $especialidades = $em->createQuery($dql);
        return $especialidades;
	}
}
