<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoDiagnosticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoDiagnosticoRepository extends EntityRepository
{
		public function findForPaginator(){
		$em = $this->getEntityManager();
		
		$dql = "SELECT u FROM AppBundle:Grupodiagnostico u";
        $grupoDiagnosticos = $em->createQuery($dql);
        return $grupoDiagnosticos;
	}
}
