<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListaResultadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListaResultadosRepository extends EntityRepository
{
}
