<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MotivoSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivoSolicitudRepository extends EntityRepository
{
  public function findForPaginator(){
  $em = $this->getEntityManager();

  $dql = "SELECT u FROM AppBundle:MotivoSolicitud u";
      $motivoSolicitud = $em->createQuery($dql);
      return $motivoSolicitud;
    }
}
