<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacienteRepository extends EntityRepository
{
	public function findForPaginator(){
		$em = $this->getEntityManager();
		
		$dql = "SELECT u FROM AppBundle:Paciente u";
        $pacientes = $em->createQuery($dql);
        return $pacientes;
	}
}
